# Generated by Django 2.2.6 on 2019-10-25 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Ідентифікатор')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва')),
                ('rate', models.FloatField(max_length=30, verbose_name='Базовий тариф')),
                ('rate_1', models.FloatField(max_length=30, verbose_name='Перше перевищення')),
                ('rate_2', models.FloatField(max_length=30, verbose_name='Друге перевищення')),
                ('rate_3', models.FloatField(max_length=30, verbose_name='Третє перевищення')),
                ('formula', models.CharField(max_length=300, verbose_name='Формула розрахунку')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.datetime(2019, 10, 25, 13, 11, 16, 22412, tzinfo=utc), verbose_name='Дата створення')),
                ('body', models.TextField(max_length='1000', verbose_name='Звіт')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=30, verbose_name='Показання')),
                ('date_stamp', models.DateField(default=datetime.datetime(2019, 10, 25, 13, 11, 16, 22070, tzinfo=utc), verbose_name='Дата внесення')),
                ('rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.Rates', verbose_name='Ідентифікатор')),
            ],
        ),
    ]
