# Generated by Django 2.2.6 on 2019-10-25 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0002_auto_20191025_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='formula',
            field=models.CharField(max_length=300, null=True, verbose_name='Формула розрахунку'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate_1',
            field=models.FloatField(max_length=30, null=True, verbose_name='Перше перевищення'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate_2',
            field=models.FloatField(max_length=30, null=True, verbose_name='Друге перевищення'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rate_3',
            field=models.FloatField(max_length=30, null=True, verbose_name='Третє перевищення'),
        ),
        migrations.AlterField(
            model_name='readings',
            name='date_stamp',
            field=models.DateField(default=datetime.datetime(2019, 10, 25, 13, 59, 48, 202670, tzinfo=utc), verbose_name='Дата внесення'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 25, 13, 59, 48, 202966, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
