# Generated by Django 2.2.6 on 2019-10-25 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0003_auto_20191025_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='date_stamp',
            field=models.DateField(default=datetime.datetime(2019, 10, 25, 14, 21, 57, 474148, tzinfo=utc), verbose_name='Дата внесення'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 25, 14, 21, 57, 474498, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
