# Generated by Django 2.2.6 on 2019-11-06 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0004_auto_20191025_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активність'),
        ),
        migrations.AlterField(
            model_name='readings',
            name='date_stamp',
            field=models.CharField(default='2019.11', max_length=30, verbose_name='Дата внесення'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 19, 48, 46, 985554, tzinfo=utc), verbose_name='Дата створення'),
        ),
        migrations.AlterUniqueTogether(
            name='readings',
            unique_together={('rate_id', 'date_stamp')},
        ),
    ]
