# Generated by Django 2.2.6 on 2019-11-06 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0008_auto_20191106_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активність'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 20, 8, 2, 575604, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
