# Generated by Django 2.2.6 on 2019-12-24 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0009_auto_20191106_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='date_stamp',
            field=models.CharField(default='2019.12', max_length=30, verbose_name='Дата внесення'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 24, 17, 41, 21, 352735, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
