# Generated by Django 2.2.6 on 2019-12-30 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0013_auto_20191230_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 30, 14, 26, 36, 162679, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
