# Generated by Django 2.2.6 on 2019-12-30 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0014_auto_20191230_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 30, 14, 32, 2, 668006, tzinfo=utc), verbose_name='Дата створення'),
        ),
    ]
